---
title: "Comparison of different methods for calculationg weights in epiregulon with the use of the simulated data"
author: "Tomasz Włodarczyk"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: true
    toc_depth: 3
params:
    save_results: TRUE
    save_path: ""
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```


```{r}
suppressWarnings({
    library(epiregulon.benchmark)
    library(scMultiSim)
    library(ggplot2)
    library(ggpubr)
    library(rstatix)
    library(dplyr)
})

```

```{r Epiregulon, child = system.file("reports/GRN_preparation.Rmd", package = "epiregulon.benchmark"),cache=TRUE, cache.lazy=FALSE, message=FALSE}
```
```{r}
atac.effect <- 0.5
```
```{r Epiregulon, child = system.file("reports/basic_simulation.Rmd", package = "epiregulon.benchmark"),cache=TRUE, cache.lazy=FALSE, message=FALSE}
```

```{r echo=FALSE, cache=TRUE, cache.lazy=FALSE}
data("transcription_difference_matrix")
weights_exp_cutoff = 1
weights_peak_cutoff = 0
exp_cutoff = 1
peak_cutoff = 0
tf_re.merge = TRUE

input_objects <- processSimResults(sim_res)
clusters_list <- list("lmfit" = input_objects$geneExpMatrix$label,
                      "corr" = input_objects$geneExpMatrix$label,
                      "MI" = input_objects$geneExpMatrix$label)


add_columns <- function(df, sparsity="medium", pseudobulks=FALSE,
                        ATAC_effect = "normal", counts = "Observed counts",
                        GRN_noise="uncontaminated"){
    df$sparsity <- sparsity
    df$pseudobulks <- pseudobulks
    df$ATAC_effect <- ATAC_effect
    df$counts <- counts
    df$GRN_noise <- GRN_noise
    df
}
```
```{r cache=TRUE, cache.lazy=FALSE, message=FALSE}
plot_data <- data.frame()
# Uncontaminated regulon, observed counts
plot_data_part <- runEpiregulonWorkflows(input_objects$regulon, input_objects, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          TF_expression = TRUE,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge) 

plot_data_part <- add_columns(plot_data_part)
plot_data <- rbind(plot_data, plot_data_part)

# pseudobulks
plot_data_part <- runEpiregulonWorkflows(input_objects$regulon, input_objects, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          aggregateCells = TRUE,
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff = weights_peak_cutoff,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge) 

plot_data_part <- add_columns(plot_data_part, pseudobulks=TRUE)
plot_data <- rbind(plot_data, plot_data_part)

# Contaminating regulon with 50% of false connections
set.seed(1110)
# remove part of the true connections
regulon.mixed <- addFalseConnections(input_objects$regulon, fraction_false = 0.5)

plot_data_part <- runEpiregulonWorkflows(regulon.mixed, input_objects, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = c(NA, 0.05, 0.001, 0.0001))

plot_data_part <- add_columns(plot_data_part, GRN_noise="+100% false")
plot_data <- rbind(plot_data, plot_data_part)



# Removing 50% of true connections

set.seed(1110)
# remove part of the true connections
remove_ind <- sample(1:nrow(input_objects$regulon), round(nrow(input_objects$regulon)/2))
regulon.reduced <- input_objects$regulon[-remove_ind,]

plot_data_part <- runEpiregulonWorkflows(regulon.reduced, input_objects, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = c(NA, 0.05, 0.001, 0.0001)) 

plot_data_part <- add_columns(plot_data_part, GRN_noise="-50% true")
plot_data <- rbind(plot_data, plot_data_part)

# Removing 50% of true connections and contaminating regulon with 50% of false connections
```
```{r cache=TRUE, cache.lazy=FALSE, message=FALSE}
set.seed(1110)
# remove part of the true connections
remove_ind <- sample(1:nrow(input_objects$regulon), round(nrow(input_objects$regulon)/2))
regulon.mixed <- addFalseConnections(input_objects$regulon, fraction_false = 1/3)
regulon.mixed <- regulon.mixed[-remove_ind,]

plot_data_part <- runEpiregulonWorkflows(regulon.mixed, input_objects, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = c(NA, 0.05, 0.001, 0.0001)) 

plot_data_part <- add_columns(plot_data_part, GRN_noise="-50% true\n+100% false")
plot_data <- rbind(plot_data, plot_data_part)

# Removing 50% of true connections and contaminating regulon with 2/3 of false connections

set.seed(1110)
# remove part of the true connections
remove_ind <- sample(1:nrow(input_objects$regulon), round(nrow(input_objects$regulon)/2))
regulon.mixed <- addFalseConnections(input_objects$regulon, fraction_false = 0.5)
regulon.mixed <- regulon.mixed[-remove_ind,]


plot_data_part <- runEpiregulonWorkflows(regulon.mixed, input_objects, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = c(NA, 0.05, 0.001, 0.0001)) 

plot_data_part <- add_columns(plot_data_part, GRN_noise="-50% true\n+200% false")
plot_data <- rbind(plot_data, plot_data_part)
```
```{r cache=TRUE, cache.lazy=FALSE, message=FALSE}
# true counts

plot_data_part <- runEpiregulonWorkflows(input_objects$regulon, input_objects, transcription_difference_matrix,
                          exp_assay = "norm_counts",
                          peak_assay = "peak",
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = NULL,
                          TF_expression = TRUE) 

plot_data_part <- add_columns(plot_data_part, counts="True counts")
plot_data <- rbind(plot_data, plot_data_part)


# Comparison of weight methods based on the observed counts (normalized)
## Moving cutoff


# Sparsity lesser than default

set.seed(11000)
add_expr_noise(sim_res, alpha_mean = 0.5,
               alpha_sd = 0.001, alpha_gene_mean = 1, alpha_gene_sd = 0,
               depth_mean = 2e5, depth_sd = 1e3,
               atac.obs.prob = 0.6, atac.sd.frac = 0.05, protocol = "UMI")
if(params$save_results)
saveRDS(sim_res, file.path(params$save_path, "sim_res_ls.rds"))


input_objects_ls <- processSimResults(sim_res)
## uncontaminated regulon, no pruning

plot_data_part <- runEpiregulonWorkflows(input_objects_ls$regulon, input_objects_ls, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          TF_expression = TRUE,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = NULL) 

plot_data_part <- add_columns(plot_data_part, sparsity="low")
plot_data <- rbind(plot_data, plot_data_part)


## uncontaminated regulon, no pruning, pseudobulks

plot_data_part <- runEpiregulonWorkflows(input_objects_ls$regulon, input_objects_ls, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          aggregateCells = TRUE,
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = NULL) 

plot_data_part <- add_columns(plot_data_part, sparsity="low", pseudobulks=TRUE)
plot_data <- rbind(plot_data, plot_data_part)

# Sparsity greater than default

set.seed(11000)
add_expr_noise(sim_res,  alpha_mean = 0.05,
               alpha_sd = 0.005, alpha_gene_mean = 0.75, alpha_gene_sd = 0.05,
               depth_mean = 5e4, depth_sd = 2e3,
               atac.obs.prob = 0.2, atac.sd.frac = 0.2, protocol = "UMI")

if(params$save_results)
saveRDS(sim_res, file.path(params$save_path, "sim_res_gs.rds"))

input_objects_gs <- processSimResults(sim_res)

plot_data_part <- runEpiregulonWorkflows(input_objects_gs$regulon, input_objects_gs, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          TF_expression = TRUE,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = NULL) 

plot_data_part <- add_columns(plot_data_part, sparsity="high")
plot_data <- rbind(plot_data, plot_data_part)


## uncontaminated regulon, no pruning, pseudobulks

plot_data_part <- runEpiregulonWorkflows(input_objects_gs$regulon, input_objects_gs, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          aggregateCells = TRUE,
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = NULL) 

plot_data_part <- add_columns(plot_data_part, sparsity="high", pseudobulks=TRUE)
plot_data <- rbind(plot_data, plot_data_part)

```

```{r}
# copy previous simulation results before they are overwritten
# sim_res_normal_ATAC <- sim_res
atac.effect <- 0.85
```

```{r Epiregulon, child = system.file("reports/basic_simulation.Rmd", package = "epiregulon.benchmark"),cache=TRUE, cache.lazy=FALSE}
```

```{r cache = TRUE, cache.lazy=FALSE, message=FALSE, results='hide', fig.keep='all'}
data("transcription_difference_matrix_strong_ATAC")
input_objects <- processSimResults(sim_res)

# true counts
plot_data_part <- runEpiregulonWorkflows(input_objects$regulon, input_objects, transcription_difference_matrix,
                          exp_assay = "norm_counts",
                          peak_assay = "peak",
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = NULL,
                          TF_expression = TRUE) 

plot_data_part <- add_columns(plot_data_part, ATAC_effect="strong", counts="True counts")
plot_data <- rbind(plot_data, plot_data_part)

# observed counts
plot_data_part <- runEpiregulonWorkflows(input_objects$regulon, input_objects, transcription_difference_matrix,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          weights_exp_cutoff = weights_exp_cutoff,
                          weights_peak_cutoff =weights_peak_cutoff,
                          exp_cutoff = exp_cutoff,
                          peak_cutoff = peak_cutoff,
                          tf_re.merge = tf_re.merge,
                          regulon_cutoffs = NULL,
                          TF_expression = TRUE) 

plot_data_part <- add_columns(plot_data_part, ATAC_effect="strong")
plot_data <- rbind(plot_data, plot_data_part)

set.seed(11000)
add_expr_noise(sim_res,  alpha_mean = 0.05,
               alpha_sd = 0.005, alpha_gene_mean = 0.75, alpha_gene_sd = 0.05,
               depth_mean = 5e4, depth_sd = 2e3,
               atac.obs.prob = 0.2, atac.sd.frac = 0.2, protocol = "UMI")

# strong ATAC-seq signal, greater sparsity for later use
input_objects_gs <- processSimResults(sim_res)
```

# Plots

## GRN noise
```{r fig.dim=c(4.5,4), cache=TRUE, cache.lazy=FALSE}
df <- dplyr::filter(plot_data , method !="TF expression", ATAC_effect == "normal", pseudobulks==FALSE,
                    counts=="Observed counts", sparsity=="medium", is.na(pval_cutoff))

df$GRN_noise <- factor(df$GRN_noise, levels = c("uncontaminated",
                                                "+100% false",
                                                "-50% true",
                                                "-50% true\n+100% false",
                                                "-50% true\n+200% false"))

df$method <- factor(df$method, levels = c("wilcoxon", "corr", "MI"))

dev.new()
pdf(file.path(params$save_path, "GRN_noise.pdf"), height = 5, width = 8)

ggplot(df, aes(x = method, y = correlations, fill = method))+
    geom_boxplot(lwd=0.1, outlier.size=0.1)+
    facet_wrap(~GRN_noise, ncol = 6)+
    xlab("Weights method")+
    ylab("Correlation between true and Epiregulon inferred activity")+
    ggtitle("Effect of false connections on the accuracy of TF activity")+
    theme(plot.title = element_text(hjust = 0.5),
          strip.text.x = element_text(size = 9),
          #panel.border = element_rect(color = "black", fill = NA),
          panel.background = element_rect(fill = "white", colour="black"),
          axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5, size = 10))

if(params$save_results){
    if(!dir.exists(file.path(params$save_path, "plots","simualtion"))) dir.create(file.path(params$save_path, "plots", "simualtion"))
    ggsave(file.path(params$save_path, "plots", "simulation", "GRN_noise.pdf"), width = 4.5, height = 4)
}
```


## Pseudobulks
```{r fig.dim=c(5,5)}
df <- dplyr::filter(plot_data , ATAC_effect == "normal",
                    counts=="Observed counts", is.na(pval_cutoff), GRN_noise=="uncontaminated",
                    method=="wilcoxon")

df$sparsity <- factor(df$sparsity, levels = c("low", "medium", "high"))

df %>%
    group_by(method, sparsity) %>%
    dplyr::group_map(function(x,y) {x<-x[x$tf %in% x$tf[duplicated(x$tf)],];x<-x[order(x$tf),];x<-cbind(x,data.frame(method = y[1],sparsity = y[2]));x[order(x$sparsity),]}) %>% # keep only those tfs, which are present in both groups
    {function(x) do.call(rbind, x)}() %>%
    group_by(method, sparsity) %>%
    wilcox_test(correlations~pseudobulks, paired = TRUE) %>%
    adjust_pvalue(method = "holm") %>%
    add_significance("p.adj") -> stat_tests

stat_tests <- add_xy_position(stat_tests, x= "method", dodge = 0.8, fun = "max")

boxplot_pseudobulks <- ggboxplot(df, x = "method", y= "correlations", fill = "pseudobulks",
                                 facet.by = "sparsity",lwd= 0.1, outlier.size = 0.1)+
    xlab("Weights method")+
    ylab("Correlation between true and assessed activity")+
    ggtitle("Effect of pseudobulks on Epiregulon performance\nwith various sparsity level")+
    theme(plot.title = element_text(hjust = 0.5))+
    scale_y_continuous(expand = expansion(mult = c(0.02, 0.1)))

boxplot_pseudobulks + stat_pvalue_manual(stat_tests, label = "p.adj", tip.length = 0)

if(params$save_results){
    ggsave(file.path(params$save_path, "plots", "simulation", "pseudobulks.pdf"), width = 5, height = 5)
}
```

## Varying ATAC effect
```{r fig.dim=c(5,8)}
df <- dplyr::filter(plot_data, is.na(pval_cutoff), GRN_noise=="uncontaminated", sparsity == "medium",
                    method!="TF expression", pseudobulks==FALSE)

df %>%
    group_by(method, counts) %>%
    dplyr::group_map(function(x,y) {x<-x[x$tf %in% x$tf[duplicated(x$tf)],];x<-x[order(x$tf),];x<-cbind(x,data.frame(method = y[1],counts = y[2]));x[order(x$ATAC_effect),]}) %>% # keep only those tfs, which are present in both groups
    {function(x) do.call(rbind, x)}() %>%
    group_by(method, counts) %>%
    wilcox_test(correlations~ATAC_effect, paired = TRUE) %>%
    adjust_pvalue(method = "holm") %>%
    add_significance("p.adj") -> stat_tests

df$counts <- factor(df$counts, levels = c("True counts", "Observed counts"))
df$method <- factor(df$method, levels = c("wilcoxon", "corr", "MI"))

df %>%
    group_by(method, counts) %>%
    dplyr::group_map(function(x,y) {x<-x[x$tf %in% x$tf[duplicated(x$tf)],];x<-x[order(x$tf),];x<-cbind(x,data.frame(method = y[1],counts = y[2]));x[order(x$ATAC_effect),]}) %>% # keep only those tfs, which are present in both groups
    {function(x) do.call(rbind, x)}() %>%
    group_by(method, counts) %>%
    wilcox_test(correlations~ATAC_effect, paired = TRUE) %>%
    adjust_pvalue(method = "holm") %>%
    add_significance("p.adj") -> stat_tests

stat_tests <- add_xy_position(stat_tests, x= "method", dodge = 0.8, fun = "max")

boxplot_ATAC <- ggboxplot(df, x = "method", y= "correlations", fill = "ATAC_effect",
                                 facet.by = "counts", lwd= 0.1, outlier.size = 0.1)+
    xlab("Weights method")+
    ylab("Correlation between true and assessed activity")+
    ggtitle("Varying ATACseq effect")+
    theme(plot.title = element_text(hjust = 0.5))+
    scale_y_continuous(expand = expansion(mult = c(0.02, 0.1)))

boxplot_ATAC + stat_pvalue_manual(stat_tests, label = "p.adj", tip.length = 0, size = 3.5)

if(params$save_results){
    ggsave(file.path(params$save_path, "plots", "simulation", "ATACseq_signal_effect.pdf"), width = 5, height = 8)
}
```

## Varying sparsity
```{r fig.dim=c(5,8)}
df <- dplyr::filter(plot_data, is.na(pval_cutoff), ATAC_effect == "normal", sparsity == "medium",
                    pseudobulks==FALSE)

df$sparsity <- factor(df$sparsity, levels = c("True counts","Low sparsity", "Medium sparsity", "High sparsity"))
df <- df[df$method %in% c("wilcoxon", "corr", "MI", "TF expression"),]
df$method <- factor(df$method, levels = c("wilcoxon", "corr", "MI", "TF expression"))

ggplot(df, aes(x = method, y = correlations, fill = method))+
    geom_boxplot(lwd=0.1, outlier.size=0.1)+
    facet_wrap(~sparsity, ncol = 4)+
    xlab("Weights method")+
    ylab("Correlation between true and Epiregulon inferred activity")+
    ggtitle("Epiregulon performance with different sparsity levels")+
    theme(plot.title = element_text(hjust = 0.5),
          panel.background = element_rect(fill = "white", colour="black"),
          axis.text.x = element_text(angle = 90, hjust = 1))

if(params$save_results){
    ggsave(file.path(params$save_path, "plots", "simulation", "sparsity.pdf"), width = 5, height = 8)}
```

## Pruning efficiency
```{r fig.dim=c(6.5,6.5)}

df <- dplyr::filter(plot_data, ATAC_effect == "normal", sparsity == "medium",
                    pseudobulks==FALSE, counts == "Observed counts", method!="TF expression")
epiregulon.benchmark::check_pruning_effect(df)
if(params$save_results){
    ggsave(file.path(params$save_path, "plots", "simulation", "pruning_efficiency.pdf"), width = 5, height = 8)}
```


```{r message=FALSE}
regulon <- input_objects_gs$regulon

# add contamination
set.seed(1110)
regulon <- addFalseConnections(input_objects$regulon, fraction_false = 1/2)

regulon.fixed <-  pruneRegulon(regulon = regulon,
                         expMatrix = input_objects$geneExpMatrix,
                         exp_assay = "norm_counts_obs",
                         peakMatrix = input_objects$peakMatrix,
                         peak_assay = "peak_obs",
                         test = "chi.sq",
                         clusters = input_objects$geneExpMatrix$label,
                         regulon_cutoff = 2)

RP_table <- data.frame()
for(cutoff in seq(0,3, by = 0.01)){
    TP_fixed <- sum((abs(regulon.fixed$stats[,"all"]) >= cutoff) & (regulon.fixed$connection_type == TRUE))
    FP_fixed <- sum((abs(regulon.fixed$stats[,"all"]) >= cutoff) & (regulon.fixed$connection_type == FALSE))
    FN_fixed <- sum((abs(regulon.fixed$stats[,"all"]) < cutoff) & (regulon.fixed$connection_type == TRUE))
    RP_table <- rbind(RP_table, data.frame(cutoff = cutoff,
                                           TP_fixed = TP_fixed, FP_fixed = FP_fixed, FN_fixed = FN_fixed))
}

y1 <- (RP_table$TP_fixed/(RP_table$TP_fixed + RP_table$FN_fixed))
y2 <- (RP_table$TP_fixed/(RP_table$TP_fixed + RP_table$FP_fixed))
ylim <- c(min(y1,y2)-0.01, max(y1,y2)+0.01)
plot(seq(0,3, by = 0.01), y1, xlab = "z-score cutoff (absolute value)",
     ylab = "Recall/precision", type = "l", main = "Accuracy of the pruning, observed counts", ylim=ylim)
 lines(seq(0,3, by = 0.01), y2, col = "red")
 legend(x = 0.2, y=1, c("Recall", "Precision"), col=c("red", "black"), lty = c(1,1))

if(params$save_results){
    dev.new()
    pdf(file.path(params$save_path, "plots", "simulation", "recall_precision_strong_ATAC.pdf"), width = 6, height = 6)
    y1 <- (RP_table$TP_fixed/(RP_table$TP_fixed + RP_table$FN_fixed))
    y2 <- (RP_table$TP_fixed/(RP_table$TP_fixed + RP_table$FP_fixed))
    ylim <- c(min(y1,y2)-0.01, max(y1,y2)+0.01)
    plot(seq(0,3, by = 0.01), y1, xlab = "z-score cutoff (absolute value)",
         ylab = "Recall/precision", type = "l", main = "Accuracy of the pruning, observed counts", ylim=ylim)
     lines(seq(0,3, by = 0.01), y2, col = "red")
     legend(x = 0.2, y=1, c("Recall", "Precision"), col=c("red", "black"), lty = c(1,1))
    dev.off()
}


# add column with the correlation between expression of transcription factor and target gene 
regulon <- addTfTargetCorr(regulon, input_objects$geneExpMatrix, assay_name = "norm_counts_obs")


regulon <- addReTargetCorr(regulon, input_objects$geneExpMatrix, input_objects$peakMatrix,
                           assay_name_gene = "norm_counts_obs", assay_name_peak="peak_obs")

regulon <- addTgNumb(regulon, sim_res)

if(params$save_results){
    dev.new()
    pdf(file.path(params$save_path, "plots", "simulation", "TF-TG_corr_strong_ATAC.pdf"), width = 3, height = 6)
    boxplot(regulon$tf_tg_corr[!duplicated(regulon[,c("tf", "target")])]~regulon$connection_type[!duplicated(regulon[,c("tf", "target")])],
            main = "True and false\nGRN edges", ylab = "TF-TG correlation", xlab = "Edge status")
    dev.off()
    
    dev.new()
    pdf(file.path(params$save_path, "plots", "simulation", "RE-TG_corr_strong_ATAC.pdf"), width = 3, height = 6)
    boxplot(regulon$re_tg_corr[!duplicated(regulon[,c("tf", "target")])]~regulon$connection_type[!duplicated(regulon[,c("tf", "target")])],
            main = "True and false\nGRN edges", ylab = "RE-TG correlation", xlab = "Edge status")
    dev.off()
}

boxplot(regulon$tf_tg_corr[!duplicated(regulon[,c("tf", "target")])]~regulon$connection_type[!duplicated(regulon[,c("tf", "target")])],
        main = "True and false\nGRN edges", ylab = "TF-TG correlation", xlab = "Edge status")

boxplot(regulon$re_tg_corr[!duplicated(regulon[,c("tf", "target")])]~regulon$connection_type[!duplicated(regulon[,c("tf", "target")])],
        main = "True and false\nGRN edges", ylab = "RE-TG correlation", xlab = "Edge status")

res <- accuracyComparisonPruning(regulon, input_objects, transcription_difference_matrix_strong_ATAC,
                          exp_assay = "norm_counts_obs",
                          peak_assay = "peak_obs",
                          weights_exp_cutoff = 1,
                          weights_peak_cutoff = 0,
                          exp_cutoff = 1,
                          peak_cutoff = 0,
                          tf_re.merge = TRUE,
                          regulon_cutoffs = c(2, 0.8, 0.5, 0.2, 0.1, 0.05, 1e-2, 1e-3, 1e-5, 1e-10),
                          return_intermediates = TRUE)

df <- res$df
# add column with the mean tf-tg correlation
df$tf_tg_corr <- tapply(regulon[regulon$connection_type,]$tf_tg_corr, regulon[regulon$connection_type,]$tf, mean)[as.character(df$tf)]

# add column with the mean re-tg correlation
df$re_tg_corr <- tapply(regulon[regulon$connection_type,]$re_tg_corr, regulon[regulon$connection_type,]$tf, mean)[as.character(df$tf)]

# add column with the tg per tf number
df$tg_numb <- unlist(lapply(df$tf, function(x) regulon[regulon$tf==x,"tg_numb"][1]))
```

## Relation between weights and connection status
```{r}
regulons <- res$regulon_list

for(method in names(regulons)){
    regulons[[method]]$method <- method
    regulons[[method]]$weight <- as.vector(regulons[[method]]$weight)
}
regulons <- do.call(rbind, regulons)
regulons$method <- factor(regulons$method, levels = c("wilcoxon", "corr", "MI"))


ggplot(as.data.frame(regulons), aes(x = connection_type, y = weight))+
    ggrastr::rasterise(geom_jitter(aes(color = tf_tg_corr), alpha = 0.4, width = 0.4, cex = 0.1), dpi = 100)+
    #scale_color_viridis_c(scale_name = "Correlation between\nTF and TG")+
    scale_color_viridis_c()+
    geom_boxplot(outlier.size = 0.2, fill=rgb(1,1,1,0))+
    facet_wrap(~method, nrow=1, scales = "free")+
    xlab("Edge status")+
    ylab("Weight")+
    ggtitle("Weight values comparison across different\nmethods and between edge types")+
    theme(plot.title = element_text(hjust = 0.5),
          panel.background = element_rect(fill = "white", colour="white"),
          axis.text.x = element_text(angle = 90),
          axis.text.y = element_text(size = 6))

if(params$save_results){
    ggsave(file.path(params$save_path, "plots", "simulation", "weights_by_connection_type_colTF-TG_strong_ATAC.pdf"), height = 5, width = 4)}

ggplot(as.data.frame(regulons), aes(x = connection_type, y = weight))+
    ggrastr::rasterise(geom_jitter(aes(color = re_tg_corr), alpha = 0.4, width = 0.4, size = 0.01), dpi = 100)+
    #scale_color_viridis_c(scale_name = "Correlation between\nTF and TG")+
    scale_color_viridis_c()+
    geom_boxplot(outlier.size = 0.2, fill=rgb(1,1,1,0))+
    facet_wrap(~method, nrow=1, scales = "free")+
    xlab("Edge status")+
    ylab("Weight")+
    ggtitle("Weight values comparison across different\nmethods and between edge types")+
    theme(plot.title = element_text(hjust = 0.5),
          panel.background = element_rect(fill = "white", colour="white"),
          axis.text.x = element_text(angle = 90),
          axis.text.y = element_text(size = 6))

if(params$save_results){
    ggsave(file.path(params$save_path, "plots", "simulation", "weights_by_connection_type_colRE-TG_strong_ATAC.pdf"), height = 5, width = 4)}
```


## Greater sparsity - pruning performance

```{r message=FALSE}
df <- df[df$pval_cutoff %in% c(2, 0.5, 0.2, 0.05, 0.01),]
df_new <- data.frame()
reference_all <- df[df$pval_cutoff==2,]
df <- split(df, df$pval_cutoff)
for(i in 1:length(df)){
    if(df[[i]]$pval_cutoff[1] == 2) next
    reference <- reference_all[reference_all$tf %in% df[[i]]$tf,]
    reference <- reference[match(df[[i]]$tf, reference$tf),]
    df[[i]]$correlation_delta <- df[[i]]$correlations - reference$correlations
    df[[i]]$n_tf <- length(unique((df[[i]]$tf)))
    df_new <- rbind(df_new, df[[i]])
}
df_new$pval_cutoff <- factor(df_new$pval_cutoff, levels = sort(as.numeric(unique(df_new$pval_cutoff))))
df_new <- df_new[df_new$method =="wilcoxon", ]
ggplot(df_new, aes(x = pval_cutoff, y = correlation_delta))+
    geom_jitter(aes(color = tg_numb), cex = 0.7, width = 0.3, alpha = 0.4)+
    geom_boxplot(lwd= 0.1, outlier.size = 0.1, fill=rgb(1,1,1,0))+
    scale_color_viridis_c("Regulon size")+
    #stat_summary(fun = median, geom = "label")+
    coord_flip()+
    xlab("p-value cutoff")+
    ylab("Correlation change")+
    ggtitle("Effect of the pruning\non the activity assessment accuracy")+
    theme(plot.title = element_text(hjust = 0.5),
          panel.background = element_rect(fill = "white", colour="white"))+
    geom_hline(yintercept = 0, linetype = "dashed", lwd = 0.2)

if(params$save_results){
    ggsave(file.path(params$save_path, "plots", "simulation", "pruning_performance.pdf"), height = 3.5, width = 5)}

```
